#Filename : Name of the input excel file to get the details of the type of dataset that has to be generated#
filename =Input_Data_Details.xlsx

#sheet : Name of the sheet that has to be parsed from the input excel file#
sheet=Sheet1

#json_file_name : Name of the json file that has to be parsed#
json_file_name=export_input.json

#log_file_name : Name of the logfile that has to be generated
log_file_name=data_generation_logs.log